apiVersion: v1
kind: Pod
metadata:
  name: aistor-server
spec:
  containers:
  - name: aistor-server
    image: quay.io/minio/aistor/minio:latest
    args:
    - minio
    - server
    - /mnt/data
    - --license
    - /minio.license
    ports:
    - containerPort: 9000
      hostPort: 9000
    - containerPort: 9001
      hostPort: 9001
    volumeMounts:
    - name: data
      mountPath: /mnt/data
    - name: license
      mountPath: /minio.license
    - name: certs
      mountPath: /etc/minio/certs
  volumes:
  - name: data
    hostPath:
      path: /Users/jvasdeboncoeur/minio/data
      type: DirectoryOrCreate
  - name: license
    hostPath:
      path: /Users/jvasdeboncoeur/minio/minio.license
      type: FileOrCreate
  - name: certs
    hostPath:
      path: /Users/jvasdeboncoeur/minio/certs
      type: DirectoryOrCreate
